CREATE DATABASE [AdventureWorksDWH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorksDWH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AdventureWorksDWH.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AdventureWorksDWH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AdventureWorksDWH_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorksDWH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdventureWorksDWH] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdventureWorksDWH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdventureWorksDWH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdventureWorksDWH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdventureWorksDWH] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET RECOVERY FULL 
GO

ALTER DATABASE [AdventureWorksDWH] SET  MULTI_USER 
GO

ALTER DATABASE [AdventureWorksDWH] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdventureWorksDWH] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdventureWorksDWH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdventureWorksDWH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AdventureWorksDWH] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdventureWorksDWH] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AdventureWorksDWH] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AdventureWorksDWH] SET  READ_WRITE 
GO


